module.exports = {
  RESET_RAYCASTER: "RESET_RAYCASTER",
  MOUSE_CLICK_SELECT_OBJECT_3D: "MOUSE_CLICK_SELECT_OBJECT_3D",
  RESET_CAMERA_INITIAL_POSITION: "RESET_CAMERA_INITIAL_POSITION",
  CAMERA_FINISHED_ANIMATION: "CAMERA_FINISHED_ANIMATION",
  SCENE_MODEL_SELECTED: "SCENE_MODEL_SELECTED",
  ON_RESIZE: "ON_RESIZE"
};
