module.exports = {
  RESET_RAYCASTER: "RESET_RAYCASTER",
  MOUSE_CLICK_SELECT_OBJECT_3D: "MOUSE_CLICK_SELECT_OBJECT_3D",
  HOVER_SCENE_MODEL_FROM_NAV_BAR: "HOVER_SCENE_MODEL_FROM_NAV_BAR",
  RESET_SCENE: "RESET_SCENE",
  RESET_SCENE_DETAILS: "RESET_SCENE_DETAILS",
  CAMERA_FINISHED_ANIMATION: "CAMERA_FINISHED_ANIMATION",
  CAMERA_START_ANIMATION: "CAMERA_START_ANIMATION",
  SCENE_MODEL_SELECTED: "SCENE_MODEL_SELECTED",
  ON_RESIZE: "ON_RESIZE",
  TOGGLE_AMBIENT_LIGHTING: "TOGGLE_AMBIENT_LIGHTING",
  SET_SPOTLIGHT_TARGET: "SET_SPOTLIGHT_TARGET",
  OPEN_PHOTO_SWIPE: "OPEN_PHOTO_SWIPE",
  SET_RENDER_VIDEO_TEXTURE: "SET_RENDER_VIDEO_TEXTURE"
};
