module.exports = {
  PARSE_END: "PARSE_END",
  START_SEARCH: "START_SEARCH",
  PAUSE_SEARCH: "PAUSE_SEARCH",
  STEP_FORWARD_SEARCH: "STEP_FORWARD_SEARCH",
  STEP_END_SEARCH: "STEP_END_SEARCH",
  REPLAY_SEARCH: "REPLAY_SEARCH",
  START_LOADING_GRAPH: "START_LOADING_GRAPH",
  UPDATE_SEARCH_ALGORITHM: "UPDATE_SEARCH_ALGORITHM",

  ZOOM_IN: "ZOOM_IN",
  ZOOM_OUT: "ZOOM_OUT",
  SET_GRAPH_ZOOM: "SET_GRAPH_ZOOM",

  ONZOOM_MINUS_DISABLED: "ONZOOM_MINUS_DISABLED",
  ONZOOM_MINUS_ENABLED: "ONZOOM_MINUS_ENABLED",
  ONZOOM_PLUS_DISABLED: "ONZOOM_PLUS_DISABLED",
  ONZOOM_PLUS_ENABLED: "ONZOOM_PLUS_ENABLED",

  NEXT_SEARCH_STEP: "NEXT_SEARCH_STEP",
  SEARCH_END: "SEARCH_END",

  NODES_DISCOVERED_SET: "NODES_DISCOVERED_SET",
  NODE_MONITOR_UNSET: "NODE_MONITOR_UNSET",
  NODE_MONITOR_SET: "NODE_MONITOR_SET",
  LINKS_DISCOVERED_SET: "LINKS_DISCOVERED_SET",

  UPDATE_NODE_POS: "UPDATE_NODE_POS",
  ALL_ASSETS_LOADED: "ALL_ASSETS_LOADED",
  GET_TEXTURE_ASSET: "GET_TEXTURE_ASSET"
};
