module.exports = {
  CHANGE_CAMERA: "CHANGE_CAMERA",
  SWITCH_SCENE: "SWITCH_SCENE",
  ADD_DAT_GUI_CONTROLLER: "ADD_DAT_GUI_CONTROLLER",

  LOAD_MODEL: "LOAD_MODEL",
  MODEL_LOADED: "MODEL_LOADED",
  ADD_MODEL_TO_SCENE: "ADD_MODEL_TO_SCENE",
  LOAD_NEW_SCENE: "LOAD_NEW_SCENE",
  LOAD_JSON_MODEL: "LOAD_JSON_MODEL",
  HOVER_NAVIGATION: "HOVER_NAVIGATION",
  INTERACTIVE_OBJECTS_READY: "INTERACTIVE_OBJECTS_READY"
};
