module.exports = {
  CHANGE_CAMERA: "CHANGE_CAMERA",
  SWITCH_VIEWS: "SWITCH_VIEWS",
  SET_VIEW: "SET_VIEW",
  ADD_DAT_GUI_CONTROLLER: "ADD_DAT_GUI_CONTROLLER",

  LOAD_MODEL: "LOAD_MODEL",
  MODEL_LOADED: "MODEL_LOADED",
  SCENE_DETAILS_LOADED: "SCENE_DETAILS_LOADED",
  ITEM_LOADED: "ITEM_LOADED",
  ALL_ITEMS_LOADED: "ALL_ITEMS_LOADED",
  ITEM_START_LOAD: "ITEM_START_LOAD",

  LOAD_NEW_SCENE: "LOAD_NEW_SCENE",
  ADD_MODEL_TO_SCENE: "ADD_MODEL_TO_SCENE",
  REMOVE_MODEL_FROM_SCENE: "REMOVE_MODEL_FROM_SCENE",

  LOAD_JSON_MODEL: "LOAD_JSON_MODEL",
  BUILD_SCENE_DETAILS: "BUILD_SCENE_DETAILS",
};
