module.exports = {
  ARE_ASSETS_LOADED: "ARE_ASSETS_LOADED",
  LOAD_IMAGE_TEXTURE: "LOAD_IMAGE_TEXTURE",
  LOAD_MATERIAL: "LOAD_MATERIAL",
  LOAD_VIDEO_TEXTURE: "LOAD_VIDEO_TEXTURE",
  LOAD_ENV_MAP: "LOAD_ENV_MAP",
  GET_TEXT_MESH: "GET_TEXT_MESH",
  PARSE_JSON_MODEL: "PARSE_JSON_MODEL"
};
