module.exports = {
  SIZE_VIEW_TO_TRACE_BOUNDS: "SIZE_VIEW_TO_TRACE_BOUNDS",
  GET_GRAPH_TRANSFORMS: "GET_GRAPH_TRANSFORMS",

  IS_SEARCH_COMPLETE: "IS_SEARCH_COMPLETE",
  GET_GRAPH_DATA: "GET_GRAPH_DATA",

  ARE_ASSETS_LOADED: "ARE_ASSETS_LOADED"
};
