module.exports = {
  GET_CODE_VIEW_WIDTH: "GET_CODE_VIEW_WIDTH",
  GET_HEADER_VIEW_HEIGHT: "GET_HEADER_VIEW_HEIGHT",
  GET_CANVAS_GRAPH: "GET_CANVAS_GRAPH",
  GET_CANVAS_GRAPH_VIEW_EL: "GET_CANVAS_GRAPH_VIEW_EL",
  GET_TRACE_VIEW: "GET_TRACE_VIEW",
};
